[package]
name = "smash_macro"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1", features = ["full", "extra-traits"] }
quote = "1.0"

[lib]
proc-macro = true